### ISSUE TITLE
Test case has an Error

### ISSUE THREAD

**Issue by ruslanverbelchuk** [Hounddog/hounddog.github.com#3]
1) AlbumRestTest\Controller\AlbumRestControllerTest::testCreateCanBeAccessed
Undefined variable: id

/var/www/zf2-tutorial/module/AlbumRest/src/AlbumRest/Controller/AlbumRestController.php:43
/var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractRestfulController.php:191
/var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractRestfulController.php:153
/var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:464
/var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:208
/var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php:107
/var/www/zf2-tutorial/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractRestfulController.php:104
/var/www/zf2-tutorial/module/AlbumRest/test/AlbumRestTest/Controller/AlbumRestControllerTest.php:60

FAILURES!
Tests: 6, Assertions: 5, Errors: 1.

**Comment by Hounddog** [comment]
This has been fixed with the latest update, sorry for taking so long maybe you could confirm and close this error :)
